### PR TITLE
PR: Add Support for TOML "Dotfile" Configuration

### PR DESCRIPTION
**Pull request by Fahad-Ali-Khan-ca**
**Description:**
This PR adds support for users to specify configuration options via a TOML configuration file located in their home directory (e.g., `~/.github-echo-config.toml`). This feature allows users to persist their preferred options in a config file rather than providing them through command-line arguments every time.

**Key Features:**
- [x] The tool searches for a `.toml` config file in the user's home directory.
- [x] If the config file is missing, the tool will proceed as normal without any impact.
- [x] If the config file exists but cannot be parsed, the tool will exit and display an appropriate error message.
- [x] Values in the config file are used as defaults unless overridden by command-line arguments.
- [x] Unrecognized keys in the config file are ignored to allow flexibility in user configurations.
- [x] Further testing to ensure compatibility with all existing command-line arguments.

### CODE REVIEW

**Comment by AryanK1511** [comment]
Hey @Fahad-Ali-Khan-ca! Thanks for sending in this PR. Are you sure you committed all changes since I only see a modified `README.md` file?

**Comment by Fahad-Ali-Khan-ca** [comment]
> Hey @Fahad-Ali-Khan-ca! Thanks for sending in this PR. Are you sure you committed all changes since I only see a modified `README.md` file?

Hi, yeah this is just a draft I'm currently working on the issue #46

**Comment by AryanK1511** [comment]
oh okay! Thanks for letting me know

**Comment by AryanK1511** [comment]
@Fahad-Ali-Khan-ca Thanks for working on this 🫡

**Pull request merged**
